MySQL:
  Host: 127.0.0.1
  Database: OrbitalMC
  Username: TcpIsTheBest
  Password: SSSSSSSHHHHH
  Port: 3306


Messages:
## Valid placeholders {permission}
  NO-PERMISSION: "&cYou don't have the required permission!"
## Valid placeholders {level}, {name}
  CURRENT-LEVEL: "&aYour current level is {level}"
LevelCommand:
  AdminIndex:
    - "&c/Level exp give <player> - gives EXP to player."
    - "&c/Level exp set <player> - sets the EXP to the player."
    - "&c/Level exp remove <player> - removes EXP from the player."