name: OrbitalMC
version: ${project.version}
main: me.tcpackfrequency.orbitalmc.OrbitalMC
authors: [TcpAckFrequency]
description: Core plugin for OrbitalMC featuring all the essentials.
commands:
  Balance:
  Permissions:
    aliases: [perms, perm]
  Level: